import sys
import os
from datetime import datetime
from langchain_core.chat_history import BaseChatMessageHistory
from langchain_community.chat_message_histories import ChatMessageHistory
from langchain_community.vectorstores import FAISS
from langchain_core.runnables.history import RunnableWithMessageHistory
from langchain.chains import create_history_aware_retriever, create_retrieval_chain
from langchain.chains.combine_documents import create_stuff_documents_chain
from utils.model_loader import ModelLoader
from exception.custom_exception import DeepDocException
from logger.custom_logger import CustomLogger
from prompt.prompt_library import PROMPT_REGISTRY
from model.models import PromptType

class ConversationalRag: 
    def __init__(self, session_id : str , retriever) -> None:
        try: 
            self.log = CustomLogger().get_logger(__name__)
            self.session_id = session_id
            self.retriever = retriever
            self.llm = self._load_llm()
            self.contextualize_prompt = PROMPT_REGISTRY[PromptType.CONTEXTUALIZE_ANSWER.value]
            self.qa_prompt = PROMPT_REGISTRY[PromptType.CONTEXT_QA.value]
            self.history_aware_retriever = create_history_aware_retriever(self.llm, self.retriever, self.contextualize_prompt)
            self.log.info("Created history aware retriever", session_id=self.session_id)
            self.qa_chain = create_stuff_documents_chain(self.llm, self.qa_prompt)
            self.rag_chain = create_retrieval_chain(self.history_aware_retriever, self.qa_chain)
            self.log.info("Created RAG chain", session_id=self.session_id)
            self.chain = RunnableWithMessageHistory(self.rag_chain,
                                                    self._get_session_history, 
                                                    input_message_key = "input", 
                                                    history_messages_key = "chat_history",
                                                    output_message_key = "answer")
            self.log.info("Created RunnableWithMessageHistory", session_id=self.session_id)

        except Exception as e:
            self.log.error(f"Error initializing ConversationalRag: {e}")
            raise DeepDocException("Error initializing ConversationalRag", sys)
    
    def _load_llm(self):
        try: 
            llm = ModelLoader().load_llm()
            self.log.info("LLM model loaded successfully", session_id=self.session_id)
            return llm
        except Exception as e:
            self.log.error(f"Error loading LLM: {e}")
            raise DeepDocException("Error loading LLM", sys)
    
    def _get_session_history(self, session_id:str):
        try:
            history = ChatMessageHistory(session_id=session_id)
            self.log.info("Retrieved session history", session_id=self.session_id)
            return history
        except Exception as e:
            self.log.error(f"Error getting session history: {e}")
            raise DeepDocException("Error getting session history", sys)
    
    def load_retriever_from_faiss(self, index_path: str = None):
        try:
            embeddings = ModelLoader().load_embeddings()
            if not os.path.isdir(index_path):
                raise DeepDocException(f"FAISS index path does not exist: {index_path}", sys)
            
            retriever = FAISS.load_local(index_path, embeddings).as_retriever(search_type = "similarity", search_kwargs={"k":5}) # load retriever from faiss vector store
            self.log.info("Loaded retriever from FAISS", session_id=self.session_id)
            return retriever
        except Exception as e:
            self.log.error(f"Error loading retriever from FAISS: {e}")
            raise DeepDocException("Error loading retriever from FAISS", sys)
    
    def invoke(self, question: str):
        try:
            response = self.chain.invoke(
                {"input": question},
                config = {"configurable": { "session_id": self.session_id }}
                )
            answer = response.get("answer")
            if not answer:
                self.log.warning("No answer generated by RAG chain", session_id=self.session_id)
            self.log.info("RAG chain invoked successfully", session_id=self.session_id, question=question, answer=answer)
            return response
        except Exception as e:
            self.log.error(f"Error invoking RAG chain: {e}")
            raise DeepDocException("Error invoking RAG chain", sys)
    

        
